import React from 'react';
import { createRoot } from 'react-dom/client';
import { ShieldCheck, PackageCheck, Landmark, History, Truck, Mail, Code2, Database, TestTube2 } from 'lucide-react';
import dashboard from './assets/dashboard.png';
import till from './assets/till.png';
import orders from './assets/orders.png';
import money from './assets/money-expenses.png';
import historyImg from './assets/history.png';
import management from './assets/management.png';
import './styles.css';

const cases = [
  {icon:Truck,title:'Delivery & Payment Workflow',image:orders,alt:'Orders screen showing workflow filters for collections, deliveries, recurring and completed orders',problem:'Staff needed a simple delivery process while the system handled assignments, partial payments, outstanding balances and later collections.',solution:'I designed a Claim Order → Start Job → Finish Job workflow. Staff report what happened; the application reconciles cumulative payment state and maintains linked collection records.',proof:['Compact mobile-friendly order views and workflow states','Prepayment, partial-payment and collection handling','Tests for duplicates, invalid amounts and balance agreement']},
  {icon:ShieldCheck,title:'Role-Based Security & Privacy',image:management,alt:'Management area showing administration tools and product management',problem:'Operational, staff and financial information needed protection beyond simply hiding management controls in the frontend.',solution:'I implemented PostgreSQL Row Level Security and a canonical management-access rule, then audited RLS policies, views, RPC permissions and SECURITY DEFINER functions.',proof:['Staff and management permissions separated','Backend independently enforces access rules','Automated SQL security tests; pre-release suite reported no security/integrity failures, with one understood historical-data warning']},
  {icon:PackageCheck,title:'Stock Reservation & Order Processing',image:till,alt:'Till screen showing product catalogue, stock quantities and order creation interface',problem:'Several open orders could require the same stock, creating a risk of promising inventory more than once.',solution:'I modelled ordered and reserved quantities and used PostgreSQL functions, triggers and row locking to automate allocation and protect concurrent changes.',proof:['Reservations update automatically','Closed orders retain no reservations','Integrity tests cover over-reservation and negative stock']},
  {icon:Landmark,title:'Business Operations & Financial Records',image:money,alt:'Money and Expenses screen showing company gold custody workflow',problem:'Business, purchasing and financial information needed structured records rather than disconnected manual notes.',solution:'I connected operational records across purchasing, payments, contacts and company finances, with management controls and clear user-facing workflows.',proof:['Structured operational and financial records','Clear custody and payment workflows','Management access protected by database policies']},
  {icon:History,title:'Historical Audit & Traceability',image:historyImg,alt:'History screen showing company purchases, sales, staff activity, stock and money filters',problem:'Current state alone was not enough; management needed to understand what happened, who acted and which source record a change came from.',solution:'I created structured staff activity events and History views with filters and source navigation across deliveries, purchases, stock and financial activity.',proof:['Actor, action, entity and timestamp metadata','Different visibility for staff and management','Historical-import provenance preserved rather than overwritten']}
];

function App(){return <>
<header className="hero"><nav><strong>AB</strong><div><a href="#project">Project</a><a href="#case-studies">Case studies</a><a href="#contact">Contact</a></div></nav><div className="heroInner"><p className="eyebrow">FULL-STACK WEB APPLICATION DEVELOPMENT</p><h1>Hi, I’m Arlia.<br/><span>I build practical systems around real user needs.</span></h1><p className="lead">Self-taught developer with a professional background in education, management and customer support. I enjoy turning complicated workflows into clear, secure and useful digital tools.</p><div className="actions"><a className="primary" href="#project">Explore my project</a><a className="secondary" href="mailto:arlia@hotmail.co.uk"><Mail size={18}/> Contact me</a></div></div></header>
<main>
<section className="intro" id="project"><div><p className="eyebrow">FEATURED PROJECT</p><h2>Couriers Guide / House of Vane</h2><p className="big">A full-stack business management application for an active online gaming community.</p></div><div className="projectText"><p>I designed and developed the application to replace fragmented manual processes with interconnected workflows for orders, deliveries, payments, stock, purchasing, contacts, staff activity and historical records.</p><p>The production application and source repository are private because the system contains community operational and user data. A controlled demonstration can be provided on request.</p></div></section>
<section className="showcase"><figure><img src={dashboard} alt="House of Vane dashboard showing delivery and procurement statistics"/><figcaption><b>Project dashboard.</b> A role-aware overview brings delivery, procurement and quest activity into one place.</figcaption></figure></section>
<section className="stack"><div><Code2/><span>React</span><span>JavaScript</span><span>Vite</span><span>Vercel</span></div><div><Database/><span>Supabase</span><span>PostgreSQL</span><span>SQL</span><span>RLS</span></div><div><TestTube2/><span>Testing</span><span>Debugging</span><span>Security auditing</span><span>Data integrity</span></div></section>
<section id="case-studies" className="cases"><p className="eyebrow">ENGINEERING CASE STUDIES</p><h2>From problem to tested solution</h2><p className="sectionLead">These examples show how I approach requirements, UX, data modelling, security and testing—not just which technologies I use.</p><div className="grid">{cases.map(({icon:Icon,title,image,alt,problem,solution,proof})=><article className="card" key={title}><img className="caseImage" src={image} alt={alt}/><div className="cardBody"><div className="icon"><Icon/></div><h3>{title}</h3><h4>Problem</h4><p>{problem}</p><h4>Approach</h4><p>{solution}</p><h4>Evidence</h4><ul>{proof.map(x=><li key={x}>{x}</li>)}</ul></div></article>)}</div></section>
<section className="process"><div><p className="eyebrow">HOW I WORK</p><h2>Useful software starts with understanding the workflow.</h2></div><ol><li><b>01</b><span><strong>Understand</strong>Identify the user problem and edge cases.</span></li><li><b>02</b><span><strong>Design</strong>Simplify the interface and model the data.</span></li><li><b>03</b><span><strong>Build</strong>Implement frontend, database and permissions.</span></li><li><b>04</b><span><strong>Test</strong>Check behaviour, security and data integrity.</span></li></ol></section>
<section className="about"><div><p className="eyebrow">BEYOND THE CODE</p><h2>Technical curiosity, backed by people skills.</h2></div><p>My professional experience in learning support and management has taught me to listen carefully, explain information clearly, stay calm when priorities change and design around different users’ needs. I’m now looking for fully remote opportunities in junior development, QA/software testing, technical support or related digital work.</p></section>
<section id="contact" className="contact"><p className="eyebrow">GET IN TOUCH</p><h2>Interested in how I built it?</h2><p>I’m happy to discuss the architecture, testing approach and development decisions behind the project.</p><a className="primary" href="mailto:arlia@hotmail.co.uk"><Mail size={18}/> arlia@hotmail.co.uk</a><p className="location">Banbury, UK · Open to fully remote opportunities</p></section>
</main><footer>© 2026 Arlia Britton · Portfolio</footer></>}
createRoot(document.getElementById('root')).render(<App/>);
